[package]
name = "escape-hell"
version = "0.0.1"
authors = ["Alexander <alexander.bifulco@gmail.com>"]
edition = "2018"

[dependencies]
math = { path = "math" }
graphic = { path = "graphic" }
common = { path = "common" }
context = { path = "context" }
