extern crate glutin;

use std::convert::From;
use glutin::event::ElementState;
use glutin::event::VirtualKeyCode;

pub const KEYS_COUNT: usize = 117;

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Key {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown,
}

impl From<VirtualKeyCode> for Key {
    fn from(key: VirtualKeyCode) -> Self {
        match key {
            VirtualKeyCode::Space => Key::Space,
            VirtualKeyCode::Apostrophe => Key::Apostrophe,
            VirtualKeyCode::Comma => Key::Comma,
            VirtualKeyCode::Minus => Key::Minus,
            VirtualKeyCode::Period => Key::Period,
            VirtualKeyCode::Slash => Key::Slash,
            VirtualKeyCode::Key0 => Key::Num0,
            VirtualKeyCode::Key1 => Key::Num1,
            VirtualKeyCode::Key2 => Key::Num2,
            VirtualKeyCode::Key3 => Key::Num3,
            VirtualKeyCode::Key4 => Key::Num4,
            VirtualKeyCode::Key5 => Key::Num5,
            VirtualKeyCode::Key6 => Key::Num6,
            VirtualKeyCode::Key7 => Key::Num7,
            VirtualKeyCode::Key8 => Key::Num8,
            VirtualKeyCode::Key9 => Key::Num9,
            VirtualKeyCode::Semicolon => Key::Semicolon,
            VirtualKeyCode::Equals => Key::Equal,
            VirtualKeyCode::A => Key::A,
            VirtualKeyCode::B => Key::B,
            VirtualKeyCode::C => Key::C,
            VirtualKeyCode::D => Key::D,
            VirtualKeyCode::E => Key::E,
            VirtualKeyCode::F => Key::F,
            VirtualKeyCode::G => Key::G,
            VirtualKeyCode::H => Key::H,
            VirtualKeyCode::I => Key::I,
            VirtualKeyCode::J => Key::J,
            VirtualKeyCode::K => Key::K,
            VirtualKeyCode::L => Key::L,
            VirtualKeyCode::M => Key::M,
            VirtualKeyCode::N => Key::N,
            VirtualKeyCode::O => Key::O,
            VirtualKeyCode::P => Key::P,
            VirtualKeyCode::Q => Key::Q,
            VirtualKeyCode::R => Key::R,
            VirtualKeyCode::S => Key::S,
            VirtualKeyCode::T => Key::T,
            VirtualKeyCode::U => Key::U,
            VirtualKeyCode::V => Key::V,
            VirtualKeyCode::W => Key::W,
            VirtualKeyCode::X => Key::X,
            VirtualKeyCode::Y => Key::Y,
            VirtualKeyCode::Z => Key::Z,
            VirtualKeyCode::LBracket => Key::LeftBracket,
            VirtualKeyCode::Backslash => Key::Backslash,
            VirtualKeyCode::RBracket => Key::RightBracket,
            VirtualKeyCode::Grave => Key::GraveAccent,
            VirtualKeyCode::Escape => Key::Escape,
            VirtualKeyCode::Return => Key::Enter,
            VirtualKeyCode::Tab => Key::Tab,
            VirtualKeyCode::Back => Key::Backspace,
            VirtualKeyCode::Insert => Key::Insert,
            VirtualKeyCode::Delete => Key::Delete,
            VirtualKeyCode::Right => Key::Right,
            VirtualKeyCode::Left => Key::Left,
            VirtualKeyCode::Down => Key::Down,
            VirtualKeyCode::Up => Key::Up,
            VirtualKeyCode::PageUp => Key::PageUp,
            VirtualKeyCode::PageDown => Key::PageDown,
            VirtualKeyCode::Home => Key::Home,
            VirtualKeyCode::End => Key::End,
            // VirtualKeyCode::Capslock => Key::CapsLock,
            VirtualKeyCode::Scroll => Key::ScrollLock,
            VirtualKeyCode::Numlock => Key::NumLock,
            VirtualKeyCode::Snapshot => Key::PrintScreen,
            VirtualKeyCode::Pause => Key::Pause,
            VirtualKeyCode::F1 => Key::F1,
            VirtualKeyCode::F2 => Key::F2,
            VirtualKeyCode::F3 => Key::F3,
            VirtualKeyCode::F4 => Key::F4,
            VirtualKeyCode::F5 => Key::F5,
            VirtualKeyCode::F6 => Key::F6,
            VirtualKeyCode::F7 => Key::F7,
            VirtualKeyCode::F8 => Key::F8,
            VirtualKeyCode::F9 => Key::F9,
            VirtualKeyCode::F10 => Key::F10,
            VirtualKeyCode::F11 => Key::F11,
            VirtualKeyCode::F12 => Key::F12,
            VirtualKeyCode::F13 => Key::F13,
            VirtualKeyCode::F14 => Key::F14,
            VirtualKeyCode::F15 => Key::F15,
            VirtualKeyCode::F16 => Key::F16,
            VirtualKeyCode::F17 => Key::F17,
            VirtualKeyCode::F18 => Key::F18,
            VirtualKeyCode::F19 => Key::F19,
            VirtualKeyCode::F20 => Key::F20,
            VirtualKeyCode::F21 => Key::F21,
            VirtualKeyCode::F22 => Key::F22,
            VirtualKeyCode::F23 => Key::F23,
            VirtualKeyCode::F24 => Key::F24,
            VirtualKeyCode::Numpad0 => Key::Kp0,
            VirtualKeyCode::Numpad1 => Key::Kp1,
            VirtualKeyCode::Numpad2 => Key::Kp2,
            VirtualKeyCode::Numpad3 => Key::Kp3,
            VirtualKeyCode::Numpad4 => Key::Kp4,
            VirtualKeyCode::Numpad5 => Key::Kp5,
            VirtualKeyCode::Numpad6 => Key::Kp6,
            VirtualKeyCode::Numpad7 => Key::Kp7,
            VirtualKeyCode::Numpad8 => Key::Kp8,
            VirtualKeyCode::Numpad9 => Key::Kp9,
            VirtualKeyCode::Decimal => Key::KpDecimal,
            VirtualKeyCode::Divide => Key::KpDivide,
            VirtualKeyCode::Multiply => Key::KpMultiply,
            VirtualKeyCode::Subtract => Key::KpSubtract,
            VirtualKeyCode::Add => Key::KpAdd,
            VirtualKeyCode::NumpadEnter => Key::KpEnter,
            VirtualKeyCode::NumpadEquals => Key::KpEqual,
            VirtualKeyCode::LShift => Key::LeftShift,
            VirtualKeyCode::LControl => Key::LeftControl,
            VirtualKeyCode::LAlt => Key::LeftAlt,
            VirtualKeyCode::LWin => Key::LeftSuper,
            VirtualKeyCode::RShift => Key::RightShift,
            VirtualKeyCode::RControl => Key::RightControl,
            VirtualKeyCode::RAlt => Key::RightAlt,
            VirtualKeyCode::RWin => Key::RightSuper,
            missed => {
                println!("missed: {:?}", missed);
                Key::Unknown
            }
        }
    }
}

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Action {
    Release,
    Press,
    Repeat,
}

impl From<ElementState> for Action {
    fn from(action: ElementState) -> Self {
        match action {
            ElementState::Pressed => Action::Press,
            ElementState::Released => Action::Release,
        }
    }
}

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Modifier {
    Shift,
    Control,
    Alt,
    Super,
    Unknown,
}

#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct Button {
    key: Key,
    action: Action,
    modifier: Modifier,
}

impl Button {
    pub fn new(key: Key, action: Action, modifier: Modifier) -> Self {
        Button {
            key,
            action,
            modifier,
        }
    }

    pub fn key(&self) -> &Key {
        &self.key
    }

    pub fn set_key(&mut self, key: Key) {
        self.key = key;
    }

    pub fn action(&self) -> &Action {
        &self.action
    }

    pub fn set_action(&mut self, action: Action) {
        self.action = action;
    }

    pub fn modifier(&self) -> &Modifier {
        &self.modifier
    }

    pub fn set_modifier(&mut self, modifier: Modifier) {
        self.modifier = modifier;
    }
}

impl Default for Button {
    fn default() -> Self {
        Self::new(Key::Unknown, Action::Release, Modifier::Unknown)
    }
}

pub fn keys_collection() -> [Button; KEYS_COUNT] {
    [
        Button::new(Key::Space, Action::Release, Modifier::Unknown),
        Button::new(Key::Apostrophe, Action::Release, Modifier::Unknown),
        Button::new(Key::Comma, Action::Release, Modifier::Unknown),
        Button::new(Key::Minus, Action::Release, Modifier::Unknown),
        Button::new(Key::Period, Action::Release, Modifier::Unknown),
        Button::new(Key::Slash, Action::Release, Modifier::Unknown),
        Button::new(Key::Num0, Action::Release, Modifier::Unknown),
        Button::new(Key::Num1, Action::Release, Modifier::Unknown),
        Button::new(Key::Num2, Action::Release, Modifier::Unknown),
        Button::new(Key::Num3, Action::Release, Modifier::Unknown),
        Button::new(Key::Num4, Action::Release, Modifier::Unknown),
        Button::new(Key::Num5, Action::Release, Modifier::Unknown),
        Button::new(Key::Num6, Action::Release, Modifier::Unknown),
        Button::new(Key::Num7, Action::Release, Modifier::Unknown),
        Button::new(Key::Num8, Action::Release, Modifier::Unknown),
        Button::new(Key::Num9, Action::Release, Modifier::Unknown),
        Button::new(Key::Semicolon, Action::Release, Modifier::Unknown),
        Button::new(Key::Equal, Action::Release, Modifier::Unknown),
        Button::new(Key::A, Action::Release, Modifier::Unknown),
        Button::new(Key::B, Action::Release, Modifier::Unknown),
        Button::new(Key::C, Action::Release, Modifier::Unknown),
        Button::new(Key::D, Action::Release, Modifier::Unknown),
        Button::new(Key::E, Action::Release, Modifier::Unknown),
        Button::new(Key::F, Action::Release, Modifier::Unknown),
        Button::new(Key::G, Action::Release, Modifier::Unknown),
        Button::new(Key::H, Action::Release, Modifier::Unknown),
        Button::new(Key::I, Action::Release, Modifier::Unknown),
        Button::new(Key::J, Action::Release, Modifier::Unknown),
        Button::new(Key::K, Action::Release, Modifier::Unknown),
        Button::new(Key::L, Action::Release, Modifier::Unknown),
        Button::new(Key::M, Action::Release, Modifier::Unknown),
        Button::new(Key::N, Action::Release, Modifier::Unknown),
        Button::new(Key::O, Action::Release, Modifier::Unknown),
        Button::new(Key::P, Action::Release, Modifier::Unknown),
        Button::new(Key::Q, Action::Release, Modifier::Unknown),
        Button::new(Key::R, Action::Release, Modifier::Unknown),
        Button::new(Key::S, Action::Release, Modifier::Unknown),
        Button::new(Key::T, Action::Release, Modifier::Unknown),
        Button::new(Key::U, Action::Release, Modifier::Unknown),
        Button::new(Key::V, Action::Release, Modifier::Unknown),
        Button::new(Key::W, Action::Release, Modifier::Unknown),
        Button::new(Key::X, Action::Release, Modifier::Unknown),
        Button::new(Key::Y, Action::Release, Modifier::Unknown),
        Button::new(Key::Z, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftBracket, Action::Release, Modifier::Unknown),
        Button::new(Key::Backslash, Action::Release, Modifier::Unknown),
        Button::new(Key::RightBracket, Action::Release, Modifier::Unknown),
        Button::new(Key::GraveAccent, Action::Release, Modifier::Unknown),
        Button::new(Key::Escape, Action::Release, Modifier::Unknown),
        Button::new(Key::Enter, Action::Release, Modifier::Unknown),
        Button::new(Key::Tab, Action::Release, Modifier::Unknown),
        Button::new(Key::Backspace, Action::Release, Modifier::Unknown),
        Button::new(Key::Insert, Action::Release, Modifier::Unknown),
        Button::new(Key::Delete, Action::Release, Modifier::Unknown),
        Button::new(Key::Right, Action::Release, Modifier::Unknown),
        Button::new(Key::Left, Action::Release, Modifier::Unknown),
        Button::new(Key::Down, Action::Release, Modifier::Unknown),
        Button::new(Key::Up, Action::Release, Modifier::Unknown),
        Button::new(Key::PageUp, Action::Release, Modifier::Unknown),
        Button::new(Key::PageDown, Action::Release, Modifier::Unknown),
        Button::new(Key::Home, Action::Release, Modifier::Unknown),
        Button::new(Key::End, Action::Release, Modifier::Unknown),
        Button::new(Key::CapsLock, Action::Release, Modifier::Unknown),
        Button::new(Key::ScrollLock, Action::Release, Modifier::Unknown),
        Button::new(Key::NumLock, Action::Release, Modifier::Unknown),
        Button::new(Key::PrintScreen, Action::Release, Modifier::Unknown),
        Button::new(Key::Pause, Action::Release, Modifier::Unknown),
        Button::new(Key::F1, Action::Release, Modifier::Unknown),
        Button::new(Key::F2, Action::Release, Modifier::Unknown),
        Button::new(Key::F3, Action::Release, Modifier::Unknown),
        Button::new(Key::F4, Action::Release, Modifier::Unknown),
        Button::new(Key::F5, Action::Release, Modifier::Unknown),
        Button::new(Key::F6, Action::Release, Modifier::Unknown),
        Button::new(Key::F7, Action::Release, Modifier::Unknown),
        Button::new(Key::F8, Action::Release, Modifier::Unknown),
        Button::new(Key::F9, Action::Release, Modifier::Unknown),
        Button::new(Key::F10, Action::Release, Modifier::Unknown),
        Button::new(Key::F11, Action::Release, Modifier::Unknown),
        Button::new(Key::F12, Action::Release, Modifier::Unknown),
        Button::new(Key::F13, Action::Release, Modifier::Unknown),
        Button::new(Key::F14, Action::Release, Modifier::Unknown),
        Button::new(Key::F15, Action::Release, Modifier::Unknown),
        Button::new(Key::F16, Action::Release, Modifier::Unknown),
        Button::new(Key::F17, Action::Release, Modifier::Unknown),
        Button::new(Key::F18, Action::Release, Modifier::Unknown),
        Button::new(Key::F19, Action::Release, Modifier::Unknown),
        Button::new(Key::F20, Action::Release, Modifier::Unknown),
        Button::new(Key::F21, Action::Release, Modifier::Unknown),
        Button::new(Key::F22, Action::Release, Modifier::Unknown),
        Button::new(Key::F23, Action::Release, Modifier::Unknown),
        Button::new(Key::F24, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp0, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp1, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp2, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp3, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp4, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp5, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp6, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp7, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp8, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp9, Action::Release, Modifier::Unknown),
        Button::new(Key::KpDecimal, Action::Release, Modifier::Unknown),
        Button::new(Key::KpDivide, Action::Release, Modifier::Unknown),
        Button::new(Key::KpMultiply, Action::Release, Modifier::Unknown),
        Button::new(Key::KpSubtract, Action::Release, Modifier::Unknown),
        Button::new(Key::KpAdd, Action::Release, Modifier::Unknown),
        Button::new(Key::KpEnter, Action::Release, Modifier::Unknown),
        Button::new(Key::KpEqual, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftShift, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftControl, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftAlt, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftSuper, Action::Release, Modifier::Unknown),
        Button::new(Key::RightShift, Action::Release, Modifier::Unknown),
        Button::new(Key::RightControl, Action::Release, Modifier::Unknown),
        Button::new(Key::RightAlt, Action::Release, Modifier::Unknown),
        Button::new(Key::RightSuper, Action::Release, Modifier::Unknown),
        Button::new(Key::Unknown, Action::Release, Modifier::Unknown),
    ]
}
