extern crate sdl2;

use sdl2::keyboard::Keycode;
use sdl2::keyboard::Mod;
use std::convert::From;

pub const KEYS_COUNT: usize = 118;

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Key {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Semicolon,
    Equals,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEquals,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown,
}

impl From<Keycode> for Key {
    fn from(key: Keycode) -> Self {
        match key {
            Keycode::Space => Key::Space,
            Keycode::Quote => Key::Apostrophe,
            Keycode::Comma => Key::Comma,
            Keycode::Minus => Key::Minus,
            Keycode::Period => Key::Period,
            Keycode::Slash => Key::Slash,
            Keycode::Num0 => Key::Num0,
            Keycode::Num1 => Key::Num1,
            Keycode::Num2 => Key::Num2,
            Keycode::Num3 => Key::Num3,
            Keycode::Num4 => Key::Num4,
            Keycode::Num5 => Key::Num5,
            Keycode::Num6 => Key::Num6,
            Keycode::Num7 => Key::Num7,
            Keycode::Num8 => Key::Num8,
            Keycode::Num9 => Key::Num9,
            Keycode::Semicolon => Key::Semicolon,
            Keycode::Equals => Key::Equals,
            Keycode::A => Key::A,
            Keycode::B => Key::B,
            Keycode::C => Key::C,
            Keycode::D => Key::D,
            Keycode::E => Key::E,
            Keycode::F => Key::F,
            Keycode::G => Key::G,
            Keycode::H => Key::H,
            Keycode::I => Key::I,
            Keycode::J => Key::J,
            Keycode::K => Key::K,
            Keycode::L => Key::L,
            Keycode::M => Key::M,
            Keycode::N => Key::N,
            Keycode::O => Key::O,
            Keycode::P => Key::P,
            Keycode::Q => Key::Q,
            Keycode::R => Key::R,
            Keycode::S => Key::S,
            Keycode::T => Key::T,
            Keycode::U => Key::U,
            Keycode::V => Key::V,
            Keycode::W => Key::W,
            Keycode::X => Key::X,
            Keycode::Y => Key::Y,
            Keycode::Z => Key::Z,
            Keycode::LeftBracket => Key::LeftBracket,
            Keycode::Backslash => Key::Backslash,
            Keycode::RightBracket => Key::RightBracket,
            Keycode::Backquote => Key::GraveAccent,
            Keycode::Escape => Key::Escape,
            Keycode::Return => Key::Enter,
            Keycode::Tab => Key::Tab,
            Keycode::Backspace => Key::Backspace,
            Keycode::Insert => Key::Insert,
            Keycode::Delete => Key::Delete,
            Keycode::Right => Key::Right,
            Keycode::Left => Key::Left,
            Keycode::Down => Key::Down,
            Keycode::Up => Key::Up,
            Keycode::PageUp => Key::PageUp,
            Keycode::PageDown => Key::PageDown,
            Keycode::Home => Key::Home,
            Keycode::End => Key::End,
            Keycode::CapsLock => Key::CapsLock,
            Keycode::ScrollLock => Key::ScrollLock,
            Keycode::NumLockClear => Key::NumLock,
            Keycode::PrintScreen => Key::PrintScreen,
            Keycode::Pause => Key::Pause,
            Keycode::F1 => Key::F1,
            Keycode::F2 => Key::F2,
            Keycode::F3 => Key::F3,
            Keycode::F4 => Key::F4,
            Keycode::F5 => Key::F5,
            Keycode::F6 => Key::F6,
            Keycode::F7 => Key::F7,
            Keycode::F8 => Key::F8,
            Keycode::F9 => Key::F9,
            Keycode::F10 => Key::F10,
            Keycode::F11 => Key::F11,
            Keycode::F12 => Key::F12,
            Keycode::F13 => Key::F13,
            Keycode::F14 => Key::F14,
            Keycode::F15 => Key::F15,
            Keycode::F16 => Key::F16,
            Keycode::F17 => Key::F17,
            Keycode::F18 => Key::F18,
            Keycode::F19 => Key::F19,
            Keycode::F20 => Key::F20,
            Keycode::F21 => Key::F21,
            Keycode::F22 => Key::F22,
            Keycode::F23 => Key::F23,
            Keycode::F24 => Key::F24,
            Keycode::Kp0 => Key::Kp0,
            Keycode::Kp1 => Key::Kp1,
            Keycode::Kp2 => Key::Kp2,
            Keycode::Kp3 => Key::Kp3,
            Keycode::Kp4 => Key::Kp4,
            Keycode::Kp5 => Key::Kp5,
            Keycode::Kp6 => Key::Kp6,
            Keycode::Kp7 => Key::Kp7,
            Keycode::Kp8 => Key::Kp8,
            Keycode::Kp9 => Key::Kp9,
            Keycode::KpDecimal => Key::KpDecimal,
            Keycode::KpDivide => Key::KpDivide,
            Keycode::KpMultiply => Key::KpMultiply,
            Keycode::KpMemSubtract => Key::KpSubtract,
            Keycode::KpMemAdd => Key::KpAdd,
            Keycode::KpEnter => Key::KpEnter,
            Keycode::KpEquals => Key::KpEquals,
            Keycode::LShift => Key::LeftShift,
            Keycode::LCtrl => Key::LeftControl,
            Keycode::LAlt => Key::LeftAlt,
            Keycode::LGui => Key::LeftSuper,
            Keycode::RShift => Key::RightShift,
            Keycode::RCtrl => Key::RightControl,
            Keycode::RAlt => Key::RightAlt,
            Keycode::RGui => Key::RightSuper,
            missed => {
                println!("missed key: {:?}", missed);
                Key::Unknown
            }
        }
    }
}

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Action {
    Release,
    Press,
    Repeat,
}

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum Modifier {
    Shift,
    Control,
    Alt,
    Super,
    Unknown,
}

impl From<Mod> for Modifier {
    fn from(action: Mod) -> Self {
        match action {
            Mod::LSHIFTMOD => Modifier::Shift,
            Mod::LCTRLMOD => Modifier::Control,
            Mod::LALTMOD => Modifier::Alt,
            Mod::LGUIMOD => Modifier::Super,
            missed => {
                println!("missed modifier: {:?}", missed);
                Modifier::Unknown
            }
        }
    }
}

#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct Button {
    key: Key,
    action: Action,
    modifier: Modifier,
}

impl Button {
    pub fn new(key: Key, action: Action, modifier: Modifier) -> Self {
        Button {
            key,
            action,
            modifier,
        }
    }

    pub fn key(&self) -> &Key {
        &self.key
    }

    pub fn set_key(&mut self, key: Key) {
        self.key = key;
    }

    pub fn action(&self) -> &Action {
        &self.action
    }

    pub fn set_action(&mut self, action: Action) {
        self.action = action;
    }

    pub fn modifier(&self) -> &Modifier {
        &self.modifier
    }

    pub fn set_modifier(&mut self, modifier: Modifier) {
        self.modifier = modifier;
    }
}

impl Default for Button {
    fn default() -> Self {
        Self::new(Key::Unknown, Action::Release, Modifier::Unknown)
    }
}

pub fn keys_collection() -> [Button; KEYS_COUNT] {
    [
        Button::new(Key::Space, Action::Release, Modifier::Unknown),
        Button::new(Key::Apostrophe, Action::Release, Modifier::Unknown),
        Button::new(Key::Comma, Action::Release, Modifier::Unknown),
        Button::new(Key::Minus, Action::Release, Modifier::Unknown),
        Button::new(Key::Period, Action::Release, Modifier::Unknown),
        Button::new(Key::Slash, Action::Release, Modifier::Unknown),
        Button::new(Key::Num0, Action::Release, Modifier::Unknown),
        Button::new(Key::Num1, Action::Release, Modifier::Unknown),
        Button::new(Key::Num2, Action::Release, Modifier::Unknown),
        Button::new(Key::Num3, Action::Release, Modifier::Unknown),
        Button::new(Key::Num4, Action::Release, Modifier::Unknown),
        Button::new(Key::Num5, Action::Release, Modifier::Unknown),
        Button::new(Key::Num6, Action::Release, Modifier::Unknown),
        Button::new(Key::Num7, Action::Release, Modifier::Unknown),
        Button::new(Key::Num8, Action::Release, Modifier::Unknown),
        Button::new(Key::Num9, Action::Release, Modifier::Unknown),
        Button::new(Key::Semicolon, Action::Release, Modifier::Unknown),
        Button::new(Key::Equals, Action::Release, Modifier::Unknown),
        Button::new(Key::A, Action::Release, Modifier::Unknown),
        Button::new(Key::B, Action::Release, Modifier::Unknown),
        Button::new(Key::C, Action::Release, Modifier::Unknown),
        Button::new(Key::D, Action::Release, Modifier::Unknown),
        Button::new(Key::E, Action::Release, Modifier::Unknown),
        Button::new(Key::F, Action::Release, Modifier::Unknown),
        Button::new(Key::G, Action::Release, Modifier::Unknown),
        Button::new(Key::H, Action::Release, Modifier::Unknown),
        Button::new(Key::I, Action::Release, Modifier::Unknown),
        Button::new(Key::J, Action::Release, Modifier::Unknown),
        Button::new(Key::K, Action::Release, Modifier::Unknown),
        Button::new(Key::L, Action::Release, Modifier::Unknown),
        Button::new(Key::M, Action::Release, Modifier::Unknown),
        Button::new(Key::N, Action::Release, Modifier::Unknown),
        Button::new(Key::O, Action::Release, Modifier::Unknown),
        Button::new(Key::P, Action::Release, Modifier::Unknown),
        Button::new(Key::Q, Action::Release, Modifier::Unknown),
        Button::new(Key::R, Action::Release, Modifier::Unknown),
        Button::new(Key::S, Action::Release, Modifier::Unknown),
        Button::new(Key::T, Action::Release, Modifier::Unknown),
        Button::new(Key::U, Action::Release, Modifier::Unknown),
        Button::new(Key::V, Action::Release, Modifier::Unknown),
        Button::new(Key::W, Action::Release, Modifier::Unknown),
        Button::new(Key::X, Action::Release, Modifier::Unknown),
        Button::new(Key::Y, Action::Release, Modifier::Unknown),
        Button::new(Key::Z, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftBracket, Action::Release, Modifier::Unknown),
        Button::new(Key::Backslash, Action::Release, Modifier::Unknown),
        Button::new(Key::RightBracket, Action::Release, Modifier::Unknown),
        Button::new(Key::GraveAccent, Action::Release, Modifier::Unknown),
        Button::new(Key::Escape, Action::Release, Modifier::Unknown),
        Button::new(Key::Enter, Action::Release, Modifier::Unknown),
        Button::new(Key::Tab, Action::Release, Modifier::Unknown),
        Button::new(Key::Backspace, Action::Release, Modifier::Unknown),
        Button::new(Key::Insert, Action::Release, Modifier::Unknown),
        Button::new(Key::Delete, Action::Release, Modifier::Unknown),
        Button::new(Key::Right, Action::Release, Modifier::Unknown),
        Button::new(Key::Left, Action::Release, Modifier::Unknown),
        Button::new(Key::Down, Action::Release, Modifier::Unknown),
        Button::new(Key::Up, Action::Release, Modifier::Unknown),
        Button::new(Key::PageUp, Action::Release, Modifier::Unknown),
        Button::new(Key::PageDown, Action::Release, Modifier::Unknown),
        Button::new(Key::Home, Action::Release, Modifier::Unknown),
        Button::new(Key::End, Action::Release, Modifier::Unknown),
        Button::new(Key::CapsLock, Action::Release, Modifier::Unknown),
        Button::new(Key::CapsLock, Action::Release, Modifier::Unknown),
        Button::new(Key::ScrollLock, Action::Release, Modifier::Unknown),
        Button::new(Key::NumLock, Action::Release, Modifier::Unknown),
        Button::new(Key::PrintScreen, Action::Release, Modifier::Unknown),
        Button::new(Key::Pause, Action::Release, Modifier::Unknown),
        Button::new(Key::F1, Action::Release, Modifier::Unknown),
        Button::new(Key::F2, Action::Release, Modifier::Unknown),
        Button::new(Key::F3, Action::Release, Modifier::Unknown),
        Button::new(Key::F4, Action::Release, Modifier::Unknown),
        Button::new(Key::F5, Action::Release, Modifier::Unknown),
        Button::new(Key::F6, Action::Release, Modifier::Unknown),
        Button::new(Key::F7, Action::Release, Modifier::Unknown),
        Button::new(Key::F8, Action::Release, Modifier::Unknown),
        Button::new(Key::F9, Action::Release, Modifier::Unknown),
        Button::new(Key::F10, Action::Release, Modifier::Unknown),
        Button::new(Key::F11, Action::Release, Modifier::Unknown),
        Button::new(Key::F12, Action::Release, Modifier::Unknown),
        Button::new(Key::F13, Action::Release, Modifier::Unknown),
        Button::new(Key::F14, Action::Release, Modifier::Unknown),
        Button::new(Key::F15, Action::Release, Modifier::Unknown),
        Button::new(Key::F16, Action::Release, Modifier::Unknown),
        Button::new(Key::F17, Action::Release, Modifier::Unknown),
        Button::new(Key::F18, Action::Release, Modifier::Unknown),
        Button::new(Key::F19, Action::Release, Modifier::Unknown),
        Button::new(Key::F20, Action::Release, Modifier::Unknown),
        Button::new(Key::F21, Action::Release, Modifier::Unknown),
        Button::new(Key::F22, Action::Release, Modifier::Unknown),
        Button::new(Key::F23, Action::Release, Modifier::Unknown),
        Button::new(Key::F24, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp0, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp1, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp2, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp3, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp4, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp5, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp6, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp7, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp8, Action::Release, Modifier::Unknown),
        Button::new(Key::Kp9, Action::Release, Modifier::Unknown),
        Button::new(Key::KpDecimal, Action::Release, Modifier::Unknown),
        Button::new(Key::KpDivide, Action::Release, Modifier::Unknown),
        Button::new(Key::KpMultiply, Action::Release, Modifier::Unknown),
        Button::new(Key::KpSubtract, Action::Release, Modifier::Unknown),
        Button::new(Key::KpAdd, Action::Release, Modifier::Unknown),
        Button::new(Key::KpEnter, Action::Release, Modifier::Unknown),
        Button::new(Key::KpEquals, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftShift, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftControl, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftAlt, Action::Release, Modifier::Unknown),
        Button::new(Key::LeftSuper, Action::Release, Modifier::Unknown),
        Button::new(Key::RightShift, Action::Release, Modifier::Unknown),
        Button::new(Key::RightControl, Action::Release, Modifier::Unknown),
        Button::new(Key::RightAlt, Action::Release, Modifier::Unknown),
        Button::new(Key::RightSuper, Action::Release, Modifier::Unknown),
        Button::new(Key::Unknown, Action::Release, Modifier::Unknown),
    ]
}
